// Generated by gencpp from file slam_planner/LowCmd.msg
// DO NOT EDIT!


#ifndef SLAM_PLANNER_MESSAGE_LOWCMD_H
#define SLAM_PLANNER_MESSAGE_LOWCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <slam_planner/MotorCmd.h>
#include <slam_planner/LED.h>
#include <slam_planner/Cartesian.h>

namespace slam_planner
{
template <class ContainerAllocator>
struct LowCmd_
{
  typedef LowCmd_<ContainerAllocator> Type;

  LowCmd_()
    : levelFlag(0)
    , commVersion(0)
    , robotID(0)
    , SN(0)
    , bandWidth(0)
    , motorCmd()
    , led()
    , wirelessRemote()
    , reserve(0)
    , crc(0)
    , ff()  {
      wirelessRemote.assign(0);
  }
  LowCmd_(const ContainerAllocator& _alloc)
    : levelFlag(0)
    , commVersion(0)
    , robotID(0)
    , SN(0)
    , bandWidth(0)
    , motorCmd()
    , led()
    , wirelessRemote()
    , reserve(0)
    , crc(0)
    , ff()  {
  (void)_alloc;
      motorCmd.assign( ::slam_planner::MotorCmd_<ContainerAllocator> (_alloc));

      led.assign( ::slam_planner::LED_<ContainerAllocator> (_alloc));

      wirelessRemote.assign(0);

      ff.assign( ::slam_planner::Cartesian_<ContainerAllocator> (_alloc));
  }



   typedef uint8_t _levelFlag_type;
  _levelFlag_type levelFlag;

   typedef uint16_t _commVersion_type;
  _commVersion_type commVersion;

   typedef uint16_t _robotID_type;
  _robotID_type robotID;

   typedef uint32_t _SN_type;
  _SN_type SN;

   typedef uint8_t _bandWidth_type;
  _bandWidth_type bandWidth;

   typedef boost::array< ::slam_planner::MotorCmd_<ContainerAllocator> , 20>  _motorCmd_type;
  _motorCmd_type motorCmd;

   typedef boost::array< ::slam_planner::LED_<ContainerAllocator> , 4>  _led_type;
  _led_type led;

   typedef boost::array<uint8_t, 40>  _wirelessRemote_type;
  _wirelessRemote_type wirelessRemote;

   typedef uint32_t _reserve_type;
  _reserve_type reserve;

   typedef uint32_t _crc_type;
  _crc_type crc;

   typedef boost::array< ::slam_planner::Cartesian_<ContainerAllocator> , 4>  _ff_type;
  _ff_type ff;





  typedef boost::shared_ptr< ::slam_planner::LowCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slam_planner::LowCmd_<ContainerAllocator> const> ConstPtr;

}; // struct LowCmd_

typedef ::slam_planner::LowCmd_<std::allocator<void> > LowCmd;

typedef boost::shared_ptr< ::slam_planner::LowCmd > LowCmdPtr;
typedef boost::shared_ptr< ::slam_planner::LowCmd const> LowCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slam_planner::LowCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slam_planner::LowCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slam_planner::LowCmd_<ContainerAllocator1> & lhs, const ::slam_planner::LowCmd_<ContainerAllocator2> & rhs)
{
  return lhs.levelFlag == rhs.levelFlag &&
    lhs.commVersion == rhs.commVersion &&
    lhs.robotID == rhs.robotID &&
    lhs.SN == rhs.SN &&
    lhs.bandWidth == rhs.bandWidth &&
    lhs.motorCmd == rhs.motorCmd &&
    lhs.led == rhs.led &&
    lhs.wirelessRemote == rhs.wirelessRemote &&
    lhs.reserve == rhs.reserve &&
    lhs.crc == rhs.crc &&
    lhs.ff == rhs.ff;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slam_planner::LowCmd_<ContainerAllocator1> & lhs, const ::slam_planner::LowCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slam_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slam_planner::LowCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slam_planner::LowCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_planner::LowCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slam_planner::LowCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_planner::LowCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slam_planner::LowCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slam_planner::LowCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "357432b2562edd0a8e89b9c9f5fc4821";
  }

  static const char* value(const ::slam_planner::LowCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x357432b2562edd0aULL;
  static const uint64_t static_value2 = 0x8e89b9c9f5fc4821ULL;
};

template<class ContainerAllocator>
struct DataType< ::slam_planner::LowCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slam_planner/LowCmd";
  }

  static const char* value(const ::slam_planner::LowCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slam_planner::LowCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 levelFlag\n"
"uint16 commVersion\n"
"uint16 robotID\n"
"uint32 SN\n"
"uint8 bandWidth\n"
"MotorCmd[20] motorCmd\n"
"LED[4] led\n"
"uint8[40] wirelessRemote\n"
"uint32 reserve\n"
"uint32 crc\n"
"\n"
"Cartesian[4] ff               # will delete\n"
"================================================================================\n"
"MSG: slam_planner/MotorCmd\n"
"uint8 mode           # motor target mode\n"
"float32 q            # motor target position\n"
"float32 dq           # motor target velocity\n"
"float32 tau          # motor target torque\n"
"float32 Kp           # motor spring stiffness coefficient\n"
"float32 Kd           # motor damper coefficient\n"
"uint32[3] reserve    # motor target torque\n"
"================================================================================\n"
"MSG: slam_planner/LED\n"
"uint8 r\n"
"uint8 g\n"
"uint8 b\n"
"================================================================================\n"
"MSG: slam_planner/Cartesian\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::slam_planner::LowCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slam_planner::LowCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.levelFlag);
      stream.next(m.commVersion);
      stream.next(m.robotID);
      stream.next(m.SN);
      stream.next(m.bandWidth);
      stream.next(m.motorCmd);
      stream.next(m.led);
      stream.next(m.wirelessRemote);
      stream.next(m.reserve);
      stream.next(m.crc);
      stream.next(m.ff);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LowCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slam_planner::LowCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slam_planner::LowCmd_<ContainerAllocator>& v)
  {
    s << indent << "levelFlag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.levelFlag);
    s << indent << "commVersion: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.commVersion);
    s << indent << "robotID: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.robotID);
    s << indent << "SN: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.SN);
    s << indent << "bandWidth: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bandWidth);
    s << indent << "motorCmd[]" << std::endl;
    for (size_t i = 0; i < v.motorCmd.size(); ++i)
    {
      s << indent << "  motorCmd[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::slam_planner::MotorCmd_<ContainerAllocator> >::stream(s, indent + "    ", v.motorCmd[i]);
    }
    s << indent << "led[]" << std::endl;
    for (size_t i = 0; i < v.led.size(); ++i)
    {
      s << indent << "  led[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::slam_planner::LED_<ContainerAllocator> >::stream(s, indent + "    ", v.led[i]);
    }
    s << indent << "wirelessRemote[]" << std::endl;
    for (size_t i = 0; i < v.wirelessRemote.size(); ++i)
    {
      s << indent << "  wirelessRemote[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.wirelessRemote[i]);
    }
    s << indent << "reserve: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.reserve);
    s << indent << "crc: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.crc);
    s << indent << "ff[]" << std::endl;
    for (size_t i = 0; i < v.ff.size(); ++i)
    {
      s << indent << "  ff[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::slam_planner::Cartesian_<ContainerAllocator> >::stream(s, indent + "    ", v.ff[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAM_PLANNER_MESSAGE_LOWCMD_H
